-- 코드를 입력하세요
SELECT 
    RR.REST_ID, 
    REST_NAME, 
    FOOD_TYPE, 
    FAVORITES, 
    ADDRESS, 
    ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM 
    REST_REVIEW RR
JOIN
    REST_INFO RI
ON RR.REST_ID = RI.REST_ID
GROUP BY 
    REST_ID
HAVING
    ADDRESS LIKE "서울%"
ORDER BY
    SCORE DESC,
    FAVORITES DESC