-- 코드를 작성해주세요
SELECT 
    ID,
    GENOTYPE,
    PARENT_GENOTYPE
FROM 
    ECOLI_DATA C
JOIN
    (SELECT ID AS PARENT_ID, GENOTYPE AS PARENT_GENOTYPE FROM ECOLI_DATA) P
ON C.PARENT_ID = P.PARENT_ID
WHERE 
    GENOTYPE & PARENT_GENOTYPE = PARENT_GENOTYPE
ORDER BY
    ID ASC